// Code generated by protoc-gen-go.
// source: unixfs.proto
// DO NOT EDIT!

/*
Package unixfs_pb is a generated protocol buffer package.

It is generated from these files:
	unixfs.proto

It has these top-level messages:
	Data
	Metadata
*/
package unixfs_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Data_DataType int32

const (
	Data_Raw       Data_DataType = 0
	Data_Directory Data_DataType = 1
	Data_File      Data_DataType = 2
	Data_Metadata  Data_DataType = 3
	Data_Symlink   Data_DataType = 4
)

var Data_DataType_name = map[int32]string{
	0: "Raw",
	1: "Directory",
	2: "File",
	3: "Metadata",
	4: "Symlink",
}
var Data_DataType_value = map[string]int32{
	"Raw":       0,
	"Directory": 1,
	"File":      2,
	"Metadata":  3,
	"Symlink":   4,
}

func (x Data_DataType) Enum() *Data_DataType {
	p := new(Data_DataType)
	*p = x
	return p
}
func (x Data_DataType) String() string {
	return proto.EnumName(Data_DataType_name, int32(x))
}
func (x *Data_DataType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Data_DataType_value, data, "Data_DataType")
	if err != nil {
		return err
	}
	*x = Data_DataType(value)
	return nil
}
func (Data_DataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Data struct {
	Type             *Data_DataType `protobuf:"varint,1,req,name=Type,json=type,enum=unixfs.pb.Data_DataType" json:"Type,omitempty"`
	Data             []byte         `protobuf:"bytes,2,opt,name=Data,json=data" json:"Data,omitempty"`
	Filesize         *uint64        `protobuf:"varint,3,opt,name=filesize" json:"filesize,omitempty"`
	Blocksizes       []uint64       `protobuf:"varint,4,rep,name=blocksizes" json:"blocksizes,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetType() Data_DataType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Data_Raw
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetFilesize() uint64 {
	if m != nil && m.Filesize != nil {
		return *m.Filesize
	}
	return 0
}

func (m *Data) GetBlocksizes() []uint64 {
	if m != nil {
		return m.Blocksizes
	}
	return nil
}

type Metadata struct {
	MimeType         *string `protobuf:"bytes,1,req,name=MimeType,json=mimeType" json:"MimeType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Metadata) GetMimeType() string {
	if m != nil && m.MimeType != nil {
		return *m.MimeType
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "unixfs.pb.Data")
	proto.RegisterType((*Metadata)(nil), "unixfs.pb.Metadata")
	proto.RegisterEnum("unixfs.pb.Data_DataType", Data_DataType_name, Data_DataType_value)
}

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0xcf, 0x4e, 0xc4, 0x20,
	0x10, 0xc6, 0xa5, 0x4c, 0xb2, 0x74, 0xac, 0x86, 0xcc, 0x89, 0x78, 0x30, 0x4d, 0x0f, 0x66, 0x0f,
	0xa6, 0x07, 0x9f, 0x61, 0xa3, 0xa7, 0xbd, 0xa0, 0x2f, 0xc0, 0xae, 0x6c, 0x42, 0xfa, 0x87, 0xa6,
	0xc5, 0x68, 0x7d, 0x47, 0xdf, 0x49, 0x50, 0x5b, 0xf7, 0x32, 0xc9, 0x6f, 0x7e, 0xf0, 0x7d, 0x80,
	0xc5, 0x5b, 0xef, 0x3e, 0x4e, 0x53, 0x3d, 0x8c, 0x3e, 0x78, 0xca, 0x17, 0x3a, 0x54, 0x5f, 0x0c,
	0x61, 0x67, 0x82, 0xa1, 0x7b, 0x84, 0x97, 0x79, 0xb0, 0x8a, 0x95, 0xd9, 0xf6, 0xfa, 0x41, 0xd5,
	0xeb, 0x91, 0x3a, 0xe9, 0x9f, 0x91, 0xbc, 0x86, 0x10, 0x27, 0xd1, 0xef, 0x2d, 0x95, 0x95, 0x6c,
	0x5b, 0x68, 0x78, 0x4d, 0x09, 0x37, 0x28, 0x4e, 0xae, 0xb5, 0x93, 0xfb, 0xb4, 0x8a, 0xc7, 0x3d,
	0xe8, 0x95, 0xe9, 0x16, 0xf1, 0xd0, 0xfa, 0x63, 0x93, 0x60, 0x52, 0x50, 0xf2, 0x68, 0xcf, 0x36,
	0xd5, 0x13, 0x8a, 0xa5, 0x81, 0x36, 0xc8, 0xb5, 0x79, 0x97, 0x17, 0x74, 0x85, 0xf9, 0xce, 0x8d,
	0xf6, 0x18, 0xfc, 0x38, 0x4b, 0x46, 0x02, 0xe1, 0x31, 0xe6, 0xc9, 0x8c, 0x0a, 0x14, 0x7b, 0x1b,
	0x4c, 0x6a, 0x95, 0x9c, 0x2e, 0x71, 0xf3, 0x3c, 0x77, 0xad, 0xeb, 0x1b, 0x09, 0xd5, 0xdd, 0xbf,
	0x4a, 0x0f, 0xda, 0xbb, 0xce, 0xae, 0xdf, 0xca, 0xb5, 0xe8, 0xfe, 0xf8, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x66, 0xd1, 0x09, 0x89, 0x11, 0x01, 0x00, 0x00,
}
